# Generated by Django 5.2.17 on 2026-09-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=100, verbose_name='Tên nước')),
                ('capital_name', models.CharField(max_length=100, verbose_name='Tên thủ đô')),
                ('continent', models.CharField(max_length=50, verbose_name='Châu lục')),
                ('url_flag', models.CharField(max_length=255, verbose_name='URL quốc kỳ')),
            ],
            options={
                'verbose_name': 'Quốc gia',
                'verbose_name_plural': 'Các quốc gia',
                'ordering': ['country_name'],
            },
        ),
    ]
